CREATE TABLE [dbo].[Role](
    [RoleID] [INT] IDENTITY (1,1) NOT NULL,
	[RoleDescription] [NVARCHAR](200) NOT NULL,
	[RoleState] [BIT] NOT NULL DEFAULT 1,
	[CreationDate] [DATETIME] NOT NULL,
	[CreationUser] [NVARCHAR](50) NOT NULL,
	[UpdateDate] [DATETIME] NOT NULL,
	[UpdateUser] [NVARCHAR](50) NOT NULL,
CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
